### ISSUE TITLE
Security check does not work properly with "dev" packages

### ISSUE THREAD

**Issue by sharpcode-mthaler** [enlightn/security-checker#11]
The problem is that all occurrences of "v" in the version string are replaced by nothing. 
This leads to the version "dev-master" becoming "de-master":
https://github.com/enlightn/security-checker/blob/ba15c4cc33499f2652f788273b7cf73cc174e7dc/src/Composer.php#L38

And therefore the implemented comparison in "isDevPackage" never matches:
https://github.com/enlightn/security-checker/blob/ba15c4cc33499f2652f788273b7cf73cc174e7dc/src/AdvisoryAnalyzer.php#L109

Apart from that, the ending delimiter is missing in this regular expression:
https://github.com/enlightn/security-checker/blob/ba15c4cc33499f2652f788273b7cf73cc174e7dc/src/AdvisoryAnalyzer.php#L42

**Comment by paras-malhotra** [comment]
Thanks for reporting this @sharpcode-mthaler. Would you like to attempt a PR for this?

**Comment by paras-malhotra** [comment]
@sharpcode-mthaler this is now fixed in v1.5.1. Thanks!

**Comment by sharpcode-mthaler** [comment]
@paras-malhotra Many thanks for that quick fix!
