### ISSUE TITLE
feature request: add a way to whitelist security issues

### ISSUE THREAD

**Issue by mjrider** [enlightn/security-checker#20]
Sometimes the real world happens, and you want to whitelist a security issue. There are multiple valid reasons for doing this like
for example the code path with the vulnerability isn't reachable

i would think something like would work, 
`--whitelist identifier`  where identifier could be a CVE or GHSA or other ID

**Comment by paras-malhotra** [comment]
I'd accept a PR to make this possible, perhaps by adding another method in `AdvisoryParser` to exclude some advisories. Would suggest we name the parameter `allowlist`.

**Comment by jleonardolemos** [comment]
I am having the same issue, @mjrider let me know if you are willing to do this

**Comment by mjrider** [comment]
I regret to say i do not have the time at the moment for building this feature. If this is still open when i have time i would be willing

**Comment by paras-malhotra** [comment]
I'll keep this open for a while in case someone would like to help. Totally fine to open an issue for a feature request.

**Comment by jleonardolemos** [comment]
I just did a PR to allow CVEs: https://github.com/enlightn/security-checker/pull/21
I needed to add a title verification too because some CVEs does not have the CVE code

**Comment by paras-malhotra** [comment]
@mjrider, this is now available in v1.9.0, thanks to @jleonardolemos. 🎉
