### ISSUE TITLE
Incompatibility with newest Symfony Console version

### ISSUE THREAD

**Issue by AlexSBlackburn** [enlightn/security-checker#33]
Error:
PHP Fatal error:  Declaration of Enlightn\SecurityChecker\SecurityCheckerCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /Users/alexblackburn/Packages/security-checker/src/SecurityCheckerCommand.php on line 60

Explanation:

The inherited method `execute()` is missing the int return type, which causes a fatal error.

Versions:

PHP 8.2.10
Enlightn 1.11.0

Steps to reproduce:

```
git clone https://github.com/enlightn/security-checker.git
cd security-checker
composer install
php security-checker security:check composer.lock
```

**Comment by paras-malhotra** [comment]
Thanks for reporting this. This issue is now fixed and released as v2.0.0.
