### ISSUE TITLE
Replace `curl -sS https://getcomposer.org/installer | php` with link to docs?

### ISSUE THREAD

**Issue by Potherca** [enlightn/security-checker#5]
First of all: thank you very much for making this available! In lieu of the Sensiolabs deprecation, it is much appriciated. 🙌

Now, to my issue...

The `security-checker` CLI file contains a line prompting people to run `curl -sS https://getcomposer.org/installer | php`.

For a security package, I find this in rather poor judgment. 

I would strongly suggest that it would be better to just direct users to `https://getcomposer.org/download/` and ask them to follow the instructions there.

Security issues aside, it can be confusing for users, as `composer` might be installed but simply not (yet) have run.

Less experienced users are likely to follow the suggestion ad-verbatim, which could lead to all sorts of trouble (which could easily be avoided by educating the user via the Composer install guide).

If you concur, I don't mind following up with an MR to make this happen.

**Comment by paras-malhotra** [comment]
Hi @Potherca, thanks for your feedback. Definitely concur! A PR would be awesome, thank you. 👍

**Comment by paras-malhotra** [comment]
@Potherca, I've made a PR #9 for this. Feel free to send a follow-up PR if you'd like to polish it further. Thanks!

**Comment by Potherca** [comment]
I think the current text is perfect . I hadn't been able to find time for this yet,so  many thanks for the changes!
