### ISSUE TITLE
Give some output in case no vulnerabilities are found

### ISSUE THREAD

**Issue by oliworx** [enlightn/security-checker#7]
Like "No known security vulnerabilities found.✓"

At least with one of the verbosity options.

Otherwise you don't knot if the command did something at all.

**Comment by T3N4K4** [comment]
@oliworx you can always check the return code of the command with `echo $?`.
0 = No vulnerabilities found
1 = Shows the vulnerabilities in json format
2 = Problems with packages like constraints or restrictions.

Thats at least what we noticed.

**Comment by paras-malhotra** [comment]
@oliworx I've sent a PR #8 to support ansi and json formats. This will be available in the next release later today.
